// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GVV_PR3.Models;

public partial class Clothe
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int PurchaseAmount { get; set; }

    public int Type { get; set; }

    public bool IsAvailiable { get; set; }

    public int Price { get; set; }

    public virtual ICollection<Tovar> Tovars { get; set; } = new List<Tovar>();

    public virtual Type TypeNavigation { get; set; }
}