// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GVV_PR3.Models;

public partial class Order
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public int Status { get; set; }

    public int UserId { get; set; }

    public virtual Status StatusNavigation { get; set; }

    public virtual ICollection<TovarOrder> TovarOrders { get; set; } = new List<TovarOrder>();

    public virtual User User { get; set; }
}