// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GVV_PR3.Models;

public partial class Size
{
    public int Id { get; set; }

    public string SizeStr { get; set; }

    public int SizeInt { get; set; }

    public virtual ICollection<Tovar> Tovars { get; set; } = new List<Tovar>();
}