// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GVV_PR3.Models;

public partial class Tovar
{
    public int Clothes { get; set; }

    public int Size { get; set; }

    public int AmountAvailiable { get; set; }

    public int Id { get; set; }

    public virtual Clothe ClothesNavigation { get; set; }

    public virtual Size SizeNavigation { get; set; }

    public virtual ICollection<TovarOrder> TovarOrders { get; set; } = new List<TovarOrder>();
}