// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GVV_PR3.Models;

public partial class User
{
    public int Id { get; set; }

    public string Adress { get; set; }

    public string Login { get; set; }

    public string PasswordHash { get; set; }

    public int RoleId { get; set; }

    public string Phone { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Role Role { get; set; }
}